### ISSUE TITLE
Not working for newest Gnome-Shell v40

### ISSUE THREAD

**Issue by oicydwa** [darcato/gnome-vlan-switcher#2]
I updated the metadata.json and added v40 to it, and it allowed me to activate the extension. The problem is it doesn't seem to activate after that. I have added the Vlans through the nm-connection-editor, but when I click them to activate them, the menu goes away and when i check again, it didn't activate the Vlan interface. 

This would certainly be a very welcomed extension. Probablly the most important to me of all the ones I have added. I would be willing to help however I can. My background isn't in JS, so you would have to point me in the right direction. I looked through the code, but I am definitely not versed enough in Gnome to know what would have changed. Thought I would reachh out and see if you had it on your radar to update.

**Comment by darcato** [comment]
Hello,
thanks for your interest in this extension. Unfortunately I don't have a gnome 40 system so I can't test for that version. 

Usually the behavior that you describe happens when the VLAN activation fails. If you activate the VLAN with the following command:
```
nmcli connection up your_vlan
```
does it work?

Moreover, can you check the logs and see if you find any error message? First open the logs:
```
journalctl /usr/bin/gnome-shell -f
```
and then try to toggle the vlan widget and check if you can see any message related to this extension.

**Comment by oicydwa** [comment]
Okay. I believe you are correct. I am able to get VLANs working, however I did it all manually and not with nmcli. I'm not even sure why I can't use nmcli except every time I try it says "Operation not supported" and I am unable to find out why I can't use networkmanager to bring them up. I have done all kinds of searching, and I can't even find anything related. 

I'll keep searching. I just thought maybe I couldn't tell what method your extension was using to bring up the VLANs so I (wrongfully I guess) assumed it was because the extension didn't support Gnome 40.

**Comment by oicydwa** [comment]
Okay, I got the issue resolved. It was on my end. It still needs updated in the metadata to allow for Gnome 40. I can confirm it does work just adding Gnome 40 to the metadata. If you want to update the metadata,json and then push it to Gnome extensions website, I'm sure more people would appreciate it.

**Comment by darcato** [comment]
Ok, thanks for the update! I will add version 40 to metadata.
